# Generated by Django 5.1.3 on 2024-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
