# Generated by Django 5.1.3 on 2024-11-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userattribute_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
